/**
 * @file Gitee gitee
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import { ISvgIconProps, IconWrapper } from '@icon-park/vue-next/es/runtime'

export default IconWrapper('gitee', true, (props: ISvgIconProps) => (
  <svg width={props.size} height={props.size} viewBox="0 0 48 48" fill="none">
    <path
      d="M24,48c-13.26,0 -24,-10.74 -24,-24c0,-13.26 10.74,-24 24,-24c13.26,0 24,10.74 24,24c0,13.26 -10.74,24 -24,24zM22.52,21.33c-0.66,0 -1.19,0.53 -1.19,1.19v2.96c0,0.66 0.53,1.19 1.19,1.19h8.29c0.66,0 1.19,0.53 1.19,1.18v0.59c0,1.97 -1.59,3.56 -3.56,3.56h-11.26c-0.65,0 -1.18,-0.53 -1.18,-1.19v-11.25c0,-1.97 1.59,-3.56 3.55,-3.56h16.6c0.65,0 1.18,-0.53 1.18,-1.18v-2.97c0,-0.65 -0.53,-1.18 -1.18,-1.18h-16.6c-2.35,0 -4.61,0.93 -6.28,2.6c-1.67,1.67 -2.6,3.93 -2.6,6.29v16.59c0,0.65 0.53,1.18 1.18,1.18h17.48c4.42,0 8,-3.58 8,-8v-6.81c0,-0.66 -0.53,-1.19 -1.18,-1.19v0z"
      fill={props.colors[0]}
    />
  </svg>
))
